name: Laravel CI

on:
  push:
    branches:
      - '**' 

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: laravel_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Composer Update
      run: composer update
      
    - name: Install dependencies
      run: composer install

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run migrations
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: laravel_test
        DB_USERNAME: postgres
        DB_PASSWORD: password
      run: php artisan migrate

    - name: Run tests
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: laravel_test
        DB_USERNAME: postgres
        DB_PASSWORD: password
      run: php artisan test

  create_pull_request:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref != 'refs/heads/main' && success()
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 
  
    - name: Fetch main branch
      run: git fetch origin main

    - name: Merge main branch
      run: git merge origin/main
      continue-on-error: true

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref != '' && github.head_ref || github.ref }} 
        base: main
        title: "Auto-PR: Merge ${{ github.head_ref != '' && github.head_ref || github.ref_name }} to main"
        body: |
          This is an auto-generated pull request from branch `${{ github.head_ref != '' && github.head_ref || github.ref_name }}`
          to merge changes into `main`.
        draft: false